const theatreSeats = [
  {
    id: 1,
    zone: "auditorium",
    row: "a",
    seatNumber: 1,
    price: 1,
    isAvailable: true,
  },
  {
    id: 2,
    zone: "auditorium",
    row: "a",
    seatNumber: 2,
    price: 1,
    isAvailable: true,
  },
  {
    id: 3,
    zone: "auditorium",
    row: "a",
    seatNumber: 3,
    price: 1,
    isAvailable: true,
  },
  {
    id: 4,
    zone: "auditorium",
    row: "a",
    seatNumber: 4,
    price: 1,
    isAvailable: true,
  },
  {
    id: 5,
    zone: "auditorium",
    row: "a",
    seatNumber: 5,
    price: 1,
    isAvailable: true,
  },
  {
    id: 6,
    zone: "auditorium",
    row: "a",
    seatNumber: 6,
    price: 1,
    isAvailable: true,
  },
  {
    id: 7,
    zone: "auditorium",
    row: "b",
    seatNumber: 1,
    price: 2,
    isAvailable: true,
  },
  {
    id: 8,
    zone: "auditorium",
    row: "b",
    seatNumber: 2,
    price: 1,
    isAvailable: true,
  },
  {
    id: 9,
    zone: "auditorium",
    row: "b",
    seatNumber: 3,
    price: 1,
    isAvailable: true,
  },
  {
    id: 10,
    zone: "auditorium",
    row: "b",
    seatNumber: 4,
    price: 1,
    isAvailable: true,
  },
  {
    id: 11,
    zone: "auditorium",
    row: "b",
    seatNumber: 5,
    price: 1,
    isAvailable: true,
  },
  {
    id: 12,
    zone: "auditorium",
    row: "b",
    seatNumber: 6,
    price: 1,
    isAvailable: true,
  },
  {
    id: 13,
    zone: "auditorium",
    row: "b",
    seatNumber: 7,
    price: 2,
    isAvailable: true,
  },
  {
    id: 14,
    zone: "auditorium",
    row: "c",
    seatNumber: 1,
    price: 2,
    isAvailable: true,
  },
  {
    id: 15,
    zone: "auditorium",
    row: "c",
    seatNumber: 2,
    price: 2,
    isAvailable: true,
  },
  {
    id: 16,
    zone: "auditorium",
    row: "c",
    seatNumber: 3,
    price: 1,
    isAvailable: true,
  },
  {
    id: 17,
    zone: "auditorium",
    row: "c",
    seatNumber: 4,
    price: 1,
    isAvailable: true,
  },
  {
    id: 18,
    zone: "auditorium",
    row: "c",
    seatNumber: 5,
    price: 2,
    isAvailable: true,
  },
  {
    id: 19,
    zone: "auditorium",
    row: "c",
    seatNumber: 6,
    price: 2,
    isAvailable: true,
  },
  {
    id: 20,
    zone: "auditorium",
    row: "d",
    seatNumber: 1,
    price: 3,
    isAvailable: true,
  },
  {
    id: 21,
    zone: "auditorium",
    row: "d",
    seatNumber: 2,
    price: 2,
    isAvailable: true,
  },
  {
    id: 22,
    zone: "auditorium",
    row: "d",
    seatNumber: 3,
    price: 2,
    isAvailable: true,
  },
  {
    id: 23,
    zone: "auditorium",
    row: "d",
    seatNumber: 4,
    price: 2,
    isAvailable: true,
  },
  {
    id: 24,
    zone: "auditorium",
    row: "d",
    seatNumber: 5,
    price: 3,
    isAvailable: true,
  },
  {
    id: 25,
    zone: "auditorium",
    row: "e",
    seatNumber: 1,
    price: 3,
    isAvailable: true,
  },
  {
    id: 26,
    zone: "auditorium",
    row: "e",
    seatNumber: 2,
    price: 3,
    isAvailable: true,
  },
  {
    id: 27,
    zone: "auditorium",
    row: "e",
    seatNumber: 3,
    price: 3,
    isAvailable: true,
  },
  {
    id: 28,
    zone: "auditorium",
    row: "e",
    seatNumber: 4,
    price: 3,
    isAvailable: true,
  },
  {
    id: 29,
    zone: "balcony",
    row: "a",
    seatNumber: 1,
    price: 2,
    isAvailable: true,
  },
  {
    id: 30,
    zone: "balcony",
    row: "a",
    seatNumber: 2,
    price: 2,
    isAvailable: true,
  },
  {
    id: 31,
    zone: "balcony",
    row: "a",
    seatNumber: 3,
    price: 1,
    isAvailable: true,
  },
  {
    id: 32,
    zone: "balcony",
    row: "a",
    seatNumber: 4,
    price: 1,
    isAvailable: true,
  },
  {
    id: 33,
    zone: "balcony",
    row: "a",
    seatNumber: 5,
    price: 1,
    isAvailable: true,
  },
  {
    id: 34,
    zone: "balcony",
    row: "a",
    seatNumber: 6,
    price: 2,
    isAvailable: true,
  },
  {
    id: 35,
    zone: "balcony",
    row: "a",
    seatNumber: 7,
    price: 2,
    isAvailable: true,
  },
  {
    id: 36,
    zone: "balcony",
    row: "b",
    seatNumber: 1,
    price: 3,
    isAvailable: true,
  },
  {
    id: 37,
    zone: "balcony",
    row: "b",
    seatNumber: 2,
    price: 2,
    isAvailable: true,
  },
  {
    id: 38,
    zone: "balcony",
    row: "b",
    seatNumber: 3,
    price: 2,
    isAvailable: true,
  },
  {
    id: 39,
    zone: "balcony",
    row: "b",
    seatNumber: 4,
    price: 2,
    isAvailable: true,
  },
  {
    id: 40,
    zone: "balcony",
    row: "b",
    seatNumber: 5,
    price: 2,
    isAvailable: true,
  },
  {
    id: 41,
    zone: "balcony",
    row: "b",
    seatNumber: 6,
    price: 3,
    isAvailable: true,
  },
];

export default theatreSeats;
